### ISSUE TITLE
Format should not run if the file is the same was before

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#27] opened 2023-07-21 13:33 UTC
If i open a file, add one line, delete one line, run save, it will call the format, even if the file is the same.  Its very annoying with rubocop (the format takes 2s).

**Comment by barrett-ruth** [comment] 2023-08-19 14:58
Closing this b/c of the following 3 reasons:
1. The related discussion in neovim was closed due to lack of interest, meaning the root cause won't be addressed in the near future
2. Other plugins like null-ls and others don't perform this behavior
3. The real problem is a formatter taking 2 seconds

**Closed by barrett-ruth** 2023-08-19 14:58 UTC
